name: Tags Workflow
on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  job1:
    name: Testing github env variables.
    runs-on: ubuntu-latest
    steps: 
      - name: Testing github variables.
        run: |
          GITHUB_REPOSITORY_OWNER=${{github.repository_owner}}
          GITHUB_COMMIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')
          GITHUB_TAG=${{github.ref_name}}
          echo "$GITHUB_REPOSITORY_OWNER"
          echo "$GITHUB_COMMIT_BRANCH"
          echo $GITHUB_TAG 

    
    