name: Tags Workflow
on:
  create:
     tags:
       - '*'
  workflow_dispatch:  


jobs:
  job1:
    name: Testing github env variables.
    runs-on: macos-11
    steps: 
      - name: Testing github variables.
        run: |
          GITHUB_TAG=${{github.ref_name}}
          echo "$GITHUB_COMMIT_BRANCH"
          echo $GITHUB_TAG 
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo $branch

      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run:   echo "$GITHUB_CONTEXT"      

    
    