name: Testing Environment Variables

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Copy files to aws s3
        env:
          S3_BUCKET: 'falcon-2.0'
          RELEASE_VERSION: ${GITHUB_REF#refs/*/}
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "S3_BUCKET: $S3_BUCKET"
          echo "RELEASE_VERSION: $RELEASE_VERSION"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "HOME: $HOME"